## What OS are we running?
if [[ $(uname) == "Darwin" ]]; then
    source ~/.config/zsh/zshrc-mac-os

elif command -v freebsd-version > /dev/null; then
    source "$ZSH_CUSTOM"/os/freebsd.zsh

elif command -v apt > /dev/null; then
    source ~/.config/zsh/zshrc-linux

else
    echo 'Unknown OS!'
fi

# use a history file in here
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
# make it huge, really huge.
SAVEHIST=1000000
HISTSIZE=1000000

# there is for sure still some redundancy, but ...
# setopt BANG_HIST                 # Treat the '!' character specially during expansion.
# setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
#setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
#setopt HIST_BEEP                 # Beep when accessing nonexistent history.

# alias history="history 0"

# oh-my-zsh 
export ZSH="$HOME/.oh-my-zsh"
plugins=(git zsh-syntax-highlighting encode64 fzf-zsh-plugin zsh-interactive-cd nvm kubectl microk8s)
source $ZSH/oh-my-zsh.sh

# spaceship
export SPACESHIP_FILE="$HOME/.zsh/spaceship/spaceship.zsh"
source $SPACESHIP_FILE

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# git
alias g="git"
alias gui="~/.cargo/bin/gitui"

# nvim
alias vi="nvim" 
# alias vi="nvim"

# GPG TTY
export GPG_TTY=$(tty)

# rust
#PATH=$PATH:$HOME/.cargo/bin
source $HOME/.cargo/env

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

