#### ATTENTION ####
# source this file in ~/.zshrc
# echo 'source ~/.config/zsh/zshrc' > ~/.zshrc

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# set SPACESHIP_FILE in ~/.zshrc
# for mac using brew;
# export SPACESHIP_FILE="/usr/local/opt/spaceship/spaceship.zsh"
source $SPACESHIP_FILE

## Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting encode64 fzf zsh-interactive-cd)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# git
alias g="git"
alias gui="gitui"

# nvim
alias vim="nvim" 
alias vi="nvim"

# Kubectl
alias k="kubectl"

# MiniKube
alias mk="minikube"
alias mkk="minikube kubectl"

# GPG TTY
export GPG_TTY=$(tty)

# rust
#PATH=$PATH:$HOME/.cargo/bin
source $HOME/.cargo/env

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
